### ISSUE TITLE
Revisit several questions about variables after things are more fleshed out

### ISSUE THREAD

**Issue by grgustaf** [martijnthe/jerryscript#9]
Specifically, these comments from @martijnthe:

https://github.com/martijnthe/jerryscript/pull/5#discussion_r173842251
https://github.com/martijnthe/jerryscript/pull/5#discussion_r173842543
https://github.com/martijnthe/jerryscript/pull/5#discussion_r173843550
https://github.com/martijnthe/jerryscript/pull/5#discussion_r173844201

**Comment by martijnthe** [comment]
Sounds good, thanks :D

**Comment by martijnthe** [comment]
Moved to https://github.com/jerryscript-project/jerryscript-debugger-ts/issues/7
